### ISSUE TITLE
which javascript version to use ?

### ISSUE THREAD

**Issue by vsimko** [mattburns/exiftool.js#33]
https://github.com/mattburns/exiftool.js/blob/24361008c35ab8434fc21e017687a9e76e0ed3b4/exiftool.js#L708

The code seems to be ECMAScript 5.1 compliant, only this line contains ES6 style function definition.
I would suggest to slowly migrate to ES6.
Anyway, it should be clearly stated e.g. in `README.md` which javascript version is used for the project.

**Comment by mattburns** [comment]
Fixed by pr #37
