### ISSUE TITLE
duplicate declaration in EXIF.TiffTags 0x0132

### ISSUE THREAD

**Issue by vsimko** [mattburns/exiftool.js#36]
https://github.com/mattburns/exiftool.js/blob/24361008c35ab8434fc21e017687a9e76e0ed3b4/exiftool.js#L479-L484

**Comment by mattburns** [comment]
[Page 28 of the Exif spec](http://www.cipa.jp/std/documents/e/DC-008-Translation-2016-E.pdf) calls it `File change date and time - DateTime`  which is a pretty poor name. Exiftool (and therefore basically every piece of software) calls it `ModifyDate` which I think is a better name anyway. See https://sno.phy.queensu.ca/~phil/exiftool/TagNames/EXIF.html

I suggest we remove the `DateTime` line.
